# # -*- coding: utf-8 -*-
#
# # Form implementation generated from reading ui file 'untitled.ui'
# #
# # Created by: PyQt5 UI code generator 5.15.6
# #
# # WARNING: Any manual changes made to this file will be lost when pyuic5 is
# # run again.  Do not edit this file unless you know what you are doing.
#
#
# from PyQt5 import QtCore, QtGui, QtWidgets
#
#
# class Ui_MainWindow(object):
#     def setupUi(self, MainWindow):
#         MainWindow.setObjectName("MainWindow")
#         MainWindow.resize(800, 600)
#         self.centralwidget = QtWidgets.QWidget(MainWindow)
#         self.centralwidget.setObjectName("centralwidget")
#         self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
#         self.layoutWidget.setGeometry(QtCore.QRect(10, 13, 771, 571))
#         self.layoutWidget.setObjectName("layoutWidget")
#         self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
#         self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
#         self.horizontalLayout.setObjectName("horizontalLayout")
#         self.verticalLayout = QtWidgets.QVBoxLayout()
#         self.verticalLayout.setObjectName("verticalLayout")
#         self.CorrectnessTestButton_Slow = QtWidgets.QPushButton(self.layoutWidget)
#         self.CorrectnessTestButton_Slow.setObjectName("CorrectnessTestButton_Slow")
#         self.verticalLayout.addWidget(self.CorrectnessTestButton_Slow)
#         self.CorrectnessTestButton_Fast = QtWidgets.QPushButton(self.layoutWidget)
#         self.CorrectnessTestButton_Fast.setObjectName("CorrectnessTestButton_Fast")
#         self.verticalLayout.addWidget(self.CorrectnessTestButton_Fast)
#         self.PerformanceTestButton_Slow = QtWidgets.QPushButton(self.layoutWidget)
#         self.PerformanceTestButton_Slow.setObjectName("PerformanceTestButton_Slow")
#         self.verticalLayout.addWidget(self.PerformanceTestButton_Slow)
#         self.PerformanceTestButton_Fast = QtWidgets.QPushButton(self.layoutWidget)
#         self.PerformanceTestButton_Fast.setObjectName("PerformanceTestButton_Fast")
#         self.verticalLayout.addWidget(self.PerformanceTestButton_Fast)
#         self.horizontalLayout.addLayout(self.verticalLayout)
#         self.DrawingBoard = QtWidgets.QGraphicsView(self.layoutWidget)
#         self.DrawingBoard.setMaximumSize(QtCore.QSize(16777215, 601))
#         self.DrawingBoard.setMidLineWidth(0)
#         self.DrawingBoard.setObjectName("DrawingBoard")
#         self.horizontalLayout.addWidget(self.DrawingBoard)
#         MainWindow.setCentralWidget(self.centralwidget)
#
#         self.retranslateUi(MainWindow)
#         QtCore.QMetaObject.connectSlotsByName(MainWindow)
#
#     def retranslateUi(self, MainWindow):
#         _translate = QtCore.QCoreApplication.translate
#         MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
#         self.CorrectnessTestButton_Slow.setText(_translate("MainWindow", "n^2; n = 10"))
#         self.CorrectnessTestButton_Fast.setText(_translate("MainWindow", "(n+k)logn; n = 10"))
#         self.PerformanceTestButton_Slow.setText(_translate("MainWindow", "n^2; 10^4 pts"))
#         self.PerformanceTestButton_Fast.setText(_translate("MainWindow", "(n+k)logn; 10^4 pts"))


# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled_try.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(805, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 13, 771, 571))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.CorrectnessTestButton_Slow = QtWidgets.QPushButton(self.layoutWidget)
        self.CorrectnessTestButton_Slow.setObjectName("CorrectnessTestButton_Slow")
        self.verticalLayout.addWidget(self.CorrectnessTestButton_Slow)
        self.CorrectnessTestButton_Fast = QtWidgets.QPushButton(self.layoutWidget)
        self.CorrectnessTestButton_Fast.setObjectName("CorrectnessTestButton_Fast")
        self.verticalLayout.addWidget(self.CorrectnessTestButton_Fast)
        self.PerformanceTestButton_Slow = QtWidgets.QPushButton(self.layoutWidget)
        self.PerformanceTestButton_Slow.setObjectName("PerformanceTestButton_Slow")
        self.verticalLayout.addWidget(self.PerformanceTestButton_Slow)
        self.PerformanceTestButton_Fast = QtWidgets.QPushButton(self.layoutWidget)
        self.PerformanceTestButton_Fast.setObjectName("PerformanceTestButton_Fast")
        self.verticalLayout.addWidget(self.PerformanceTestButton_Fast)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem)
        self.DrawingBoard = QtWidgets.QGraphicsView(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.DrawingBoard.sizePolicy().hasHeightForWidth())
        self.DrawingBoard.setSizePolicy(sizePolicy)
        self.DrawingBoard.setMaximumSize(QtCore.QSize(636, 601))
        self.DrawingBoard.setMidLineWidth(0)
        self.DrawingBoard.setObjectName("DrawingBoard")
        self.horizontalLayout.addWidget(self.DrawingBoard)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CorrectnessTestButton_Slow.setText(_translate("MainWindow", "n^2; n = 10"))
        self.CorrectnessTestButton_Fast.setText(_translate("MainWindow", "(n+k)logn; n = 10"))
        self.PerformanceTestButton_Slow.setText(_translate("MainWindow", "n^2; 10^4 pts"))
        self.PerformanceTestButton_Fast.setText(_translate("MainWindow", "(n+k)logn; 10^4 pts"))
