# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 13, 771, 571))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.CorrectnessTestButton = QtWidgets.QPushButton(self.widget)
        self.CorrectnessTestButton.setObjectName("CorrectnessTestButton")
        self.verticalLayout.addWidget(self.CorrectnessTestButton)
        self.PerformanceTestButton = QtWidgets.QPushButton(self.widget)
        self.PerformanceTestButton.setObjectName("PerformanceTestButton")
        self.verticalLayout.addWidget(self.PerformanceTestButton)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.DrawingBoard = QtWidgets.QGraphicsView(self.widget)
        self.DrawingBoard.setMaximumSize(QtCore.QSize(16777215, 601))
        self.DrawingBoard.setObjectName("DrawingBoard")
        self.horizontalLayout.addWidget(self.DrawingBoard)
        self.CorrectnessTestButton.raise_()
        self.PerformanceTestButton.raise_()
        self.DrawingBoard.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CorrectnessTestButton.setText(_translate("MainWindow", "Small amount of pts"))
        self.PerformanceTestButton.setText(_translate("MainWindow", "10^4 pts"))
