# coding: utf-8

"""
    DBMS API

    DBMS API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI

from openapi_server.apis.default_api import router as DefaultApiRouter
from openapi_server.database.sql_alchemy import engine, BaseORMModel

BaseORMModel.metadata.create_all(bind=engine)

app = FastAPI(
    title="DBMS API",
    description="DBMS API",
    version="1.0.0",
)

app.include_router(DefaultApiRouter)
