# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class DatabaseCreatePostRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    DatabaseCreatePostRequest - a model defined in OpenAPI

        database_name: The database_name of this DatabaseCreatePostRequest.
    """

    database_name: str = Field()

    @validator("database_name")
    def database_name_min_length(cls, value):
        assert len(value) >= 1
        return value

DatabaseCreatePostRequest.update_forward_refs()
